#!/usr/bin/env bash
#this script are displaying

pgrep bash -l
~                                                                                                                                      
~                         
